[build]
builder = "DOCKER"
dockerfilePath = "Dockerfile"

[deploy]
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10

[env]
PORT = "80"
APP_ENV = "production"
APP_DEBUG = "false"
LOG_CHANNEL = "stderr"
DB_CONNECTION = "pgsql"
SESSION_DRIVER = "database"
CACHE_STORE = "database"
QUEUE_CONNECTION = "database"
